services:
  mysql:
    build: backend-services/database
    container_name: database
    mem_limit: 512M
    ports:
      - '8306:3306'
    networks:
      - sirchardash_piria_virtual_bank
      - sirchardash_piria_keycloak
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
      - './backend-services/database/init:/init'
    environment:
      - MYSQL_ROOT_PASSWORD=OS23D3F1N2P34aJswd
  virtual_bank:
    build: backend-services/virtual-bank
    container_name: virtual_bank
    mem_limit: 512M
    ports:
      - '8865:8080'
    networks:
      - sirchardash_piria_virtual_bank
    environment:
      - SPRING.DATASOURCE.URL=jdbc:mysql://mysql:3306/virtual_bank?serverTimezone=UTC
      - SPRING.DATASOURCE.USERNAME=virtual_bank_user
      - SPRING.DATASOURCE.PASSWORD=heckingsecure
  keycloak:
    build: backend-services/keycloak
    container_name: keycloak
    networks:
      - sirchardash_piria_keycloak
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: securecloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - '8020:8080'

volumes:
  mysql_data:
    driver: local

networks:
  sirchardash_piria_virtual_bank:
    driver: bridge
  sirchardash_piria_keycloak:
    driver: bridge
