spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:8306/museum_spinner?serverTimezone=UTC
    username: museum_user
    password: heckingsecure
  codec:
    max-in-memory-size: 32MB

keycloak:
  realm: bravesmart
  auth-server-url: http://localhost:8020/auth/
  resource: bravesmart-api
  ssl-required: 'none'
  use-resource-role-mappings: false
  disable-trust-manager: true
  bearer-only: true

server:
  port: 8081

museum-tour:
  museum:
    max-returned: 100
    refresh-cron: '* */2 * * * *'
  weather:
    cities-per-request: 3
    openweather:
      base-url: 'http://api.openweathermap.org/data/2.5/weather'
      city-list-path: 'cities.json'
      image-url: 'http://openweathermap.org/img/w/%s.png'
  geo:
    rest-countries:
      base-url: 'https://restcountries.eu/rest/v2/all'
    battuta:
      base-url: 'https://battuta.medunes.net/api/'

email:
  sender:
    host: smtp.gmail.com
    port: 587
    username: nebojsa.baabic@gmail.com
    password: zhfqtaovsdsvbokz
    protocol: smtp
    auth: true
    enable-start-tls: true
    debug: false